version: '3'
services:

  comp-mssql:
    image: "microsoft/mssql-server-linux:2017-CU5"
    volumes: 
      - db_data:/var/opt/mssql/data
    environment: 
      - ACCEPT_EULA=Y 
      - SA_PASSWORD=Password123 
      - MSSQL_PID=Express
    ports: 
      - "62000:1433"

  comp-flywaycopy:
    build: ./flyway
    depends_on: 
      - comp-mssql        
  
  comp-flyway:
    image: "boxfuse/flyway:5.1"
    command: -url=jdbc:sqlserver://comp-mssql -schemas=myschema -user=sa -password=Password123 migrate
    volumes: 
      - flyway_data:/flyway/sql
    depends_on: 
      - comp-flywaycopy             

volumes:
    db_data:
    flyway_data:    
