version: "3.6"
services:

  db:
    container_name: "compose-db"
    image: "postgres:9.6-alpine"
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "54320:5432"

  git-clone:
    container_name: "compose-flyway-git-clone"
    build: ./flyway-git-clone
    image: flyway_git_clone
    volumes:
      - flyway_git_data:/git_data
      - flyway_data:/flyway/sql
    depends_on:
      - db

  baseline:
    container_name: "compose-flyway-baseline"
    image: "boxfuse/flyway:5.1"
    command: -url=jdbc:postgresql://compose-db:5432/postgres -schemas=public -user=postgres -password=postgres baseline
    depends_on:
      - git-clone

  migrate:
    container_name: "compose-flyway-migrate"
    image: "boxfuse/flyway:5.1"
    command: -url=jdbc:postgresql://compose-db:5432/postgres -schemas=public -user=postgres -password=postgres migrate
    volumes:
      - flyway_data:/flyway/sql
    depends_on:
      - baseline

  #WEB API

  #FIZZBUZZ TO GEN DATA

  #FRONT ENDS TO QUERY DATA

volumes:
    flyway_data:
    flyway_git_data:
