version: "3.6"
services:

  db:
    container_name: "compose-db"
    image: "postgres:9.6-alpine"
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "54320:5432"

  git-clone:
    container_name: "compose-flyway-git-clone"
    build: ./flyway-git-clone
    image: flyway_git_clone
    volumes:
      - flyway_git_data:/git_data
      - flyway_data:/flyway/sql
    depends_on:
      - db

  baseline:
    container_name: "compose-flyway-baseline"
    image: "boxfuse/flyway:5.1"
    command: -url=jdbc:postgresql://compose-db:5432/postgres -schemas=public -user=postgres -password=postgres baseline
    depends_on:
      - git-clone

  migrate:
    container_name: "compose-flyway-migrate"
    image: "boxfuse/flyway:5.1"
    command: -url=jdbc:postgresql://compose-db:5432/postgres -schemas=public -user=postgres -password=postgres migrate
    volumes:
      - flyway_data:/flyway/sql
    depends_on:
      - baseline

  api:
    container_name: "compose-api"  
    image: postgrest/postgrest:v0.5.0.0
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://postgres:postgres@compose-db:5432/postgres
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: postgres #In production this role should not be the same as the one used for the connection
    depends_on:
      - db

  fizzbuzz-gen:
    container_name: "compose-fizzbuzz-gen"  
    image: carlpaton/fizzbuzz:v1.1.0
    environment:
      lowerBound: 1
      upperBound: 100
      fizzAt: 3
      buzzAt: 5   
      apiUrl: http://compose-api:3000         
    depends_on:
      - api

  #FRONT ENDS TO QUERY DATA

volumes:
    flyway_data:
    flyway_git_data:
