version: '3.6'
services:

  db:
    container_name: "compose-mssql"
    image: "microsoft/mssql-server-linux:2017-CU5"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123
      - MSSQL_PID=Express
    ports:
      - "62000:1433"

  git-clone:
    container_name: "compose-flyway-git-clone"
    build: ./flyway-git-clone
    image: flyway_git_clone
    volumes:
      - flyway_git_data:/git_data
      - flyway_data:/flyway/sql
    depends_on:
      - db

  baseline:
    container_name: "compose-flyway-baseline"
    image: "boxfuse/flyway:5.1"
    command: -url=jdbc:sqlserver://compose-mssql -schemas=fizzbuzz -user=sa -password=Password123 baseline
    depends_on:
      - git-clone
      - db

  migrate:
    container_name: "compose-flyway-migrate"
    image: "boxfuse/flyway:5.1"
    command: -url=jdbc:sqlserver://compose-mssql -schemas=fizzbuzz -user=sa -password=Password123 migrate
    volumes:
      - flyway_data:/flyway/sql
    depends_on:
      - git-clone
      - baseline
      - db

  #WEB API

  #FIZZBUZZ TO GEN DATA

  #FRONT ENDS TO QUERY DATA

volumes:
    flyway_data:
    flyway_git_data:
